export enum Status {
  INITIAL = 'INITIAL',
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR',
}

export enum ActionsEnum {
  ENRICH = 'ENRICH',
  PROCESS_DATA_ASYNC_ERROR = 'PROCESS_DATA_ASYNC_ERROR',
  PROCESS_DATA_ASYNC_SUCCESS = 'PROCESS_DATA_ASYNC_SUCCESS',
  PROCESS_DATA_ASYNC = 'PROCESS_DATA_ASYNC',
  RESET_STATE = 'RESET_STATE',
}
