export const MUSCLE_LIST = [
  'Neck',
  'Traps (trapezius)',
  'Shoulders (deltoids)',
  'Chest (pectoralis)',
  'Biceps (biceps brachii)',
  'Forearm (brachioradialis)',
  'Abs (rectus abdominis)',
  'Quads (quadriceps)',
  'Calves (gastrocnemius)',
  'Traps (trapezius)',
  'Triceps (triceps brachii)',
  'Lats (latissimus dorsi)',
  'Middle Back (rhomboids)',
  'Lower Back',
  'Glutes(gluteus maximus and medius)',
  'Quads (quadriceps)',
  'Hamstrings (biceps femoris)',
  'Calves (gastrocnemius)',
] as const;

export const EQUIPMENT = [
  'Bands',
  'Foam Roll',
  'Barbell',
  'Kettlebells',
  'Body Only',
  'Machine',
  'Cable',
  'Medicine Ball',
  'Dumbbell',
  'None',
  'E - Z Curl Bar',
  'Other',
  'Exercise Ball',
] as const;

export const EXERCISE_TYPES = [
  'Cardio',
  'Olympic Weightlifting',
  'Plyometrics',
  'Powerlifting',
  'Strength',
  'Stretching',
  'Strongman',
] as const;
