export enum SETTINGS_ACTIONS_NAMES {
  'LANGUAGE_SELECTED' = '[SETTINGS] LANGUAGE_SELECTED',
  'LANGUAGE_SELECTED_SUCCESS' = '[SETTINGS] LANGUAGE_SELECTED_SUCCESS',

  'DARK_MODE_CHANGED' = '[SETTINGS] DARK_MODE_CHANGED',
}
