import { MainLiftBlock } from './main-lift-block';

export type ProgramStatus = 'draft' | 'active' | 'completed';

/**
 * A lifter's named, saved plan for one or more Main Lift Blocks, generated by a
 * Strategy. Programs are private to the owning user and kept as history — see
 * .scratch/strength-reload-calculator/issues/02-program-lifecycle.md.
 */
export interface Program {
  id: string;
  userId: string;
  name: string;
  status: ProgramStatus;
  strategy: 'strength-reload';
  mainLiftBlocks: MainLiftBlock[];
  createdAt: number;
  updatedAt: number;
}
